name: Package CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Get changed workspaces
        id: changesets
        run: |
          # Use git diff to find changed packages
          CHANGED_WORKSPACES=$(git diff --name-only origin/main...HEAD -- packages/ | grep 'packages/' | cut -d '/' -f 2 | sort | uniq)
          echo "Changed workspaces: $CHANGED_WORKSPACES"
          echo "CHANGED_WORKSPACES=$CHANGED_WORKSPACES" >> $GITHUB_ENV

      - name: Run tests for changed packages
        if: env.CHANGED_WORKSPACES != ''
        run: pnpm -r --filter="${{ env.CHANGED_WORKSPACES }}" test
