name: Package CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install

      - name: Get changed workspaces
        id: changesets
        run: |
          echo "CHANGED_WORKSPACES=$(pnpm list --depth=-1 --json | jq -r '.[] | select(.dev !== true) | select(.updated === true) | .path' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Run tests for changed packages
        run: pnpm -r --filter="${{ env.CHANGED_WORKSPACES }}" test
